---
- name: Create the resource group
  hosts: localhost
  tasks:
    - name: Creating resource group - "{{ name }}"
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ name }}"
        location: "{{ location }}"
      register: rg
    - debug:
        var: rg
...
