---
- name: Delete the resource group
  hosts: localhost
  tasks:
    - name: Deleting resource group - "{{ name }}"
      azure.azcollection.azure_rm_resourcegroup:
        name: "{{ name }}"
        state: absent
      register: rg
    - debug:
        var: rg
