---
- hosts: localhost
  vars:
      resource_group: gmail-servicebustest
      namespace: gmail-servicebustestns
      queue: gmail-servicebustestqueue
  tasks:
    - name: Get a queue's information
      azure.azcollection.azure_rm_servicebus_info:
          type: queue
          name: "{{ queue }}"
          namespace: "{{ namespace }}"
          resource_group: "{{ resource_group }}"
          show_sas_policies: yes
      register: queue
    - debug:
          var: queue
