---
### When using the playbook, please ensure you change the keywork "gmail" as per your need. It is mandatory to do so or else it will give the error message that the name is not available
- hosts: localhost
  vars:
      resource_group: demo1-gmail-servicebustest
      location: eastus
      namespacens: demo1-gmail-servicebustestns
      queue: demo1-gmail-servicebustestqueue
  tasks:
    - name: Ensure resource group exist
      azure_rm_resourcegroup:
          name: "{{ resource_group }}"
          location: "{{ location }}"
    - name: Create a namespace
      azure_rm_servicebus:
          name: "{{ namespacens }}"
          resource_group: "{{ resource_group }}"
    - name: Create a queue
      azure_rm_servicebusqueue:
          name: "{{ queue }}"
          namespace: "{{ namespacens }}"
          resource_group: "{{ resource_group }}"
      register: queue
    - debug:
          var: queue
