---
- hosts: localhost
  vars:
      resource_group: gmail-servicebustest
      location: eastus
      namespace: gmail-servicebustestns
      topic: gmail-servicebustesttopic
  tasks:
    - name: Ensure resource group exist
      azure_rm_resourcegroup:
          name: "{{ resource_group }}"
          location: "{{ location }}"
    - name: Create a namespace
      azure_rm_servicebus:
          name: "{{ namespace }}"
          resource_group: "{{ resource_group }}"
    - name: Create a topic
      azure_rm_servicebustopic:
          name: "{{ topic }}"
          namespace: "{{ namespace }}"
          resource_group: "{{ resource_group }}"
          default_message_time_to_live_seconds: 5184000
          requires_duplicate_detection: true
          duplicate_detection_time_in_seconds: 600
          auto_delete_on_idle_in_seconds: null
      register: topic
    - debug:
          var: topic
