---
### When using the playbook, please ensure you change the keywork "gmail" as per your need. It is mandatory to do so or else it will give the error message that the name is not available
### Shared Access Signature (SAS) is a claim-based authorization mechanism using tokens. We can choose the rights for the SAS policies  from the choices - manage, listen, send, listen_send
- hosts: localhost
  vars:
      resource_group: demo-gmail-servicebustest
      namespace: demo-gmail-servicebustestns
      queue: demo-gmail-servicebustestqueue
  tasks:
    - name: Create a policy with send and listen privilege
      azure_rm_servicebussaspolicy:
          name: "{{ queue }}-policy"
          queue: "{{ queue }}"
          namespace: "{{ namespace }}"
          resource_group: "{{ resource_group }}"
          rights: listen_send
      register: policy
    - debug:
          var: policy
